// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "KeyShape",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "KeyShape",
            targets: ["AppModule"],
            bundleIdentifier: "com.Dave.test5",
            teamIdentifier: "WLW428B75Y",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .tv),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .microphone(purposeString: "The microphone improves user experience and effectiveness of the app, allowing the selection of your preference."),
                .speechRecognition(purposeString: "We ask to recognize your speech to recognize the selection of your preference.")
            ],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.v5]
)